### ISSUE TITLE
May I ask about the computing sources required?

### ISSUE THREAD

**Issue by suoych** [eric-ai-lab/VLMbench#6]
Hi, thanks for sharing your work.
May I ask how many GPUs (or the memory) it takes to train the baseline and how long the training procedure lasts for each category of tasks?

**Comment by KzZheng** [comment]
Hi suoych,

I have replied to your email. As I mentioned in the paper, I trained the model with 8 DDP A5000 GPUs and run ~2 hours each. I used batch size 16 since I found small batch sizes might cause errors.

**Comment by suoych** [comment]
> Hi suoych,
> 
> I have replied to your email. As I mentioned in the paper, I trained the model with 8 DDP A5000 GPUs and run ~2 hours each. I used batch size 16 since I found small batch sizes might cause errors.

Thanks!
