### ISSUE TITLE
Dataset about long-horizon tasks

### ISSUE THREAD

**Issue by 123penny123** [eric-ai-lab/VLMbench#7]
Hello! I am interested in obtaining the dataset about long-horizon tasks such as in Figure 1 of the paper "VLMbench: A Compositional Benchmark for Vision-and-Language Manipulation". This dataset would be extremely useful for advancing research in multi-task visual-and-language manipulation learning. If it is not possible to share the dataset, would it be possible to provide guidance on how to generate similar datasets, including long-horizon task trajectories with observations, abstract instructions, and decomposed sub-tasks? 

Thank you for your time in considering this request.

**Comment by KzZheng** [comment]
Hi, Thank you for your interest in our work. However, the long-horizon tasks shown in Figure 1 are prototypes of how our atomic tasks can be used to generate more complex tasks. Therefore, we do not include those tasks and datasets in the current VLMBench. It should be a further work.

If you are willing to build new tasks, you can refer to the current task designs, which are under 'vlm/tasks'. And use 'tools/dataset_generator_NLP.py' to generate datasets. Detailed instructions may be released future.
