### ISSUE TITLE
Task builder gets stuck

### ISSUE THREAD

**Issue by ishikasingh** [eric-ai-lab/VLMbench#9]
<img width="643" alt="Screen Shot 2023-05-12 at 6 56 04 PM" src="https://github.com/eric-ai-lab/VLMbench/assets/29032507/df5384bb-523a-4229-959c-eb1d1cdc55a3">

**Comment by KzZheng** [comment]
It seems you do not run the code under the main folder. By [this line](https://github.com/eric-ai-lab/VLMbench/blob/dfc3e531bddd933f97d2cdc16f7194d46a608edf/tools/task_builder_NLP.py#L226), the task builder will check all possible tasks under this relative path. The correct interface for stack_cubes should look like this:
![Selection_308](https://github.com/eric-ai-lab/VLMbench/assets/62070113/90336aff-c3ef-4ae4-9bfb-10cd2d55a065)

However, stack_cubes is a base task class for other tasks, and this base class cannot be executed directly. It is better to test tasks with exact variations, like stack_cubes_color. I attached a example below:

![Selection_309](https://github.com/eric-ai-lab/VLMbench/assets/62070113/8f4edcb1-69d8-458e-a775-690ed1179d81)
